### ISSUE TITLE
crow.min.css is incomplete

### ISSUE THREAD

**Issue by twistedR** [kkortes/crow#1]
```
html{
  box-sizing:border-box
}
*, *:before, *:after {
  box-sizing:inherit
}
```
The above part is missing from the min.css file provided. Without it the grids don't work.

I am not sure if you want to just add it to the documentation or if you want to add it to the sty file.

**Comment by kursusHC** [comment]
Thanks for the tip. Is this project dead ?

**Comment by twistedR** [comment]
Yeah, seems like it. The grids work fine but I haven't tested them in
mobile browsers.

**Comment by kkortes** [comment]
Hey guys. I'm extremely sorry I've not gotten back to you on this issue.

A fix for it is pushed as of today. The crow.styl, crow.css and minified css now includes the box-sizing fix to make it work properly standalone.

**Comment by kursusHC** [comment]
Thank you @kkortes ! Glad to see you're back as Crow is the best grid out there and deserve way more love.

**Comment by kkortes** [comment]
Thanks!

Yea, I've used it for my previous ~10 projects without any problems. I really hope a bigger CROWd will be using my framework soon ;)

I have some ideas for it, that might be implemented in the near future. Won't touch on the fundamentals though, just adding optional additions.
